app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

places:
    type:     rest
    resource: AppBundle\Controller\PlaceController

user:
    type:     rest
    resource: AppBundle\Controller\UserController
