user:
    type:     rest
    resource: AppBundle\Controller\UserController
greatdeal:
    type:     rest
    resource: AppBundle\Controller\GreatDealController
information:
    type:     rest
    resource: AppBundle\Controller\InformationController
tag:
    type:     rest
    resource: AppBundle\Controller\TagController
university:
    type:     rest
    resource: AppBundle\Controller\UniversityController
period:
    type:     rest
    resource: AppBundle\Controller\PeriodController
